language: python
python:
    - "3.6"
addons:
  apt:
    packages:
      - dos2unix

install:
  - pip install svn
script: "python update.py -vv -d -f"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
